import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={
                    inter.className + " relative bg-red-500 text-slate-50 p-2"
                }>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
